name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id : test
      with:
        input-1: 5
        input-2: 9

    - name: Validate // Test addition
      run: |
        [[ "${{ steps.test.outputs.addition }}" -eq 14 ]]

    - name: Validate // Test Subtraction  
      run: |
        [[ "${{ steps.test.outputs.subtraction }}" -eq -4 ]]

    - name: Validate // Test multiplication
      run: |
        [[ "${{ steps.test.outputs.multiplication }}" -eq 45 ]]
